version: "3.3"
services:
  xrd-predict:
    image: ghcr.io/cheminfo-py/xrd-tools:latest
    restart: always
    environment:
      - PORT=${PORT}
    ports:
      - 127.0.0.1:${PORT}:${PORT}
  db:
    image: mongodb
