version: "3.3"
services:
  xrd-predict:
    image: ghcr.io/cheminfo-py/xrd-tools:latest
    restart: always
    environment:
      - PORT=${PORT}
    env_file:
      - .env
    depends_on:
      - mongodb
    ports:
      - ${PORT}:${PORT}
    links:
      - mongodb
  mongodb:
    image: mongo
    mem_limit: 30000m
    memswap_limit: 30000m
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-seed/dump:/dump
