version: "2.2"
services:
  ciftools:
    image: docker.pkg.github.com/cheminfo-py/xrd-tools/xrd-tools:v0.0.2
    restart: always
    environment:
      - PORT=${PORT}
    ports:
      - 127.0.0.1:${PORT}:${PORT}
