version: "3.3"
services:
  xrd-predict:
    build: .
    restart: always
    environment:
      - PORT=${PORT}
    env_file:
      - .env
    depends_on:
      - mongodb
    ports:
      - ${PORT}:${PORT}
  mongodb:
    image: mongo
    volumes:
      - ./mongo-seed/dump:/dump
